stages:
  - verify
  - test

workflow:
  rules:
    # allow pipeline triggered by MR
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    # allow pipeline for commits in protected branches
    - if: $CI_COMMIT_REF_PROTECTED == "true"

verify:
  image: registry.gitlab.com/centos/integration/containers/tmt:latest
  stage: verify
  script:
    - tmt lint --failed-only
    - find . -name '*.sh' -not -path "*/legacy/*" | xargs -n 1 shellcheck --severity=error --shell=bash

testing-farm-job:
  stage: test
  image: quay.io/testing-farm/cli:latest
  script:
    - testing-farm request --git-ref $CI_MERGE_REQUEST_REF_PATH --git-url $CI_MERGE_REQUEST_PROJECT_URL --compose CentOS-Stream-9
