# See the documentation for more information:
# https://packit.dev/docs/configuration/

# specfile_path: compose-tests.spec

# add or remove files that should be synced
files_to_sync:
  #    - compose-tests.spec
    - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: compose-tests
# downstream (Fedora) RPM package name
downstream_package_name: compose-tests

jobs:
  - job: tests
    trigger: pull_request
    targets:
      - centos-stream-9-x86_64
    skip_build: true
    manual_trigger: true
